backend:
  name: github
  repo: SharvaParalkar/comp-arch-course
  branch: main

media_folder: "comp-arch-course/static/img"
public_folder: "/img/"

collections:
  - name: docs
    label: "Course Pages"
    folder: comp-arch-course/docs
    identifier_field: title
    extension: md
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: title, widget: string }
      - { label: "Sidebar Position", name: sidebar_position, widget: number }
      - { label: "Body", name: body, widget: markdown }