// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  lecturesSidebar: [{type: 'autogenerated', dirName: 'lectures'}],
  assignmentsSidebar: [{type: 'autogenerated', dirName: 'assignments'}],
  courseNotesSidebar: [{type: 'autogenerated', dirName: 'course-notes'}],
};

export default sidebars;
