site_name: Mostafa Akbari
tagline: Computational Designer | Architect | Architectural Technologist
copyright: © Mostafa Akbari. All rights reserved.
navigation:
  - label: About
    url: about.html
  - label: Projects
    url: projects.html
  - label: Publications
    url: publications.html
  - label: Teaching
    url: teaching.html
social_links: []
footer_links: []
default_seo:
  description: >-
    Mostafa is a distinguished computational designer and researcher with a distinctive academic background encompassing
    architectural design and computational structures. He is currently an Assistant Professor of Architecture with
    expertise in Computational Structures and Advanced Manufacturing at Texa
  og_image: ''
