site_name: OXMAN
tagline: Envision a future of complete synergy between Nature and humanity.
copyright: © OXMAN 2026. All rights reserved
navigation:
  - label: Mission
    url: mission.html
  - label: Company
    url: company.html
  - label: Work
    url: work.html
  - label: Careers
    url: careers.html
  - label: Contact
    url: contact.html
social_links:
  - label: YouTube
    url: https://www.youtube.com/channel/UCWA9MwbHMrutAzyLBYhs9KQ
  - label: LinkedIn
    url: https://www.linkedin.com/company/oxman/
  - label: Instagram
    url: https://www.instagram.com/oxmanofficial/
footer_links:
  - label: Terms and Policies
    url: terms-and-policies.html
default_seo:
  description: >-
    Envision a future of complete synergy between Nature and humanity. OXMAN is accelerating systems-level change by
    fusing design, technology, and biology in a radical shift from human-centric design to Nature-centric design.
  og_image: https://cdn.prod.website-files.com/690e0b6e2e2a0cbc45ab116e/696fe3952005ae09bb201fdc_OXMAN-OG-image.jpg
